system_prompt: You are an expert in extracting slide schemas for slides. Your task is to analyze slide HTML and create a JSON schema that captures the slide elements and their relationships. Your output should be a dictionary in JSON format, where each key-value pair strictly corresponds to the text content in a `<p>` element or the `alt` attribute of an `<img>` element.
template: |
  Please analyze the slide elements and create a structured slide schema in JSON format. You should:

  1. Understand the html representation of the slide, especially the style, layout, and the logical relationship between elements

  2. For each element, extract the following information:
    - "name": The role and feature of the element, such as "section/main/sub title", "left/right bullets", "portrait/landscape/square image", "presenters", "dates", "bolded paragraph", etc.
    - "type": Literal["text", "image"]
    - "data": List[str]
        * For text elements: The content of each paragraph, defined as text within `<p>` tags, must be treated as a single, distinct item.
          - Preserve newlines (`\n`) within paragraphs, ensuring they remain intact and are not split into multiple items. Only `<p>` tags serve as separators.
          - Do not combine multiple `<p>` tags into a single item, regardless of logical or narrative connections. Each `<p>` tag represents a separate item.
        * For image elements: Use the `alt` attribute of the <img> tag as the data of the image

  3. Do not include any empty elements, only given elements should be included
  Example Input:
  <div style="font-size: 32pt; top: 50pt; left: 100pt; width: 500pt; height: 80pt; font-weight: bold;">
    <p>text0</p>
  </div>
  <div style="font-size: 14pt; top: 150pt; left: 100pt; width: 300pt; height: 200pt;">
    <p>text1\ntext2\ntext3</p>
  </div>
    <div style="font-size: 14pt; top: 150pt; left: 600pt; width: 300pt; height: 200pt;">
    <p>text1\ntext2\ntext3</p>
  </div>
  <img alt="caption of image" src="pic.png" style="top: 150pt; left: 450pt; width: 400pt; height: 300pt;">

  Example Output:
  {
    "main title": {
      "type": "text",
      "data": ["text0"],
    },
    "left bullets": {
      "type": "text",
      "data": ["text1\ntext2\ntext3"],
    },
    "right bullets": {
      "type": "text",
      "data": ["text1\ntext2\ntext3"],
    },
    "main image": {
      "type": "image",
      "data": ["caption of image"],
    }
  }
  Example format:
  {
    "element_name": {
      "type": "text" or "image",
      "data": ["text1", "text2"] or ["logo:...", "logo:..."]
    }
  }
  Input:
  {{slide}}

  Output: Please provide the slide schema in a dict of JSON format

jinja_args:
  - slide

use_model: language
return_json: True
